# Generated by Django 2.1.7 on 2023-05-15 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230514_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 14, 23, 27, 41, 971394)),
        ),
    ]
